spring:
  profiles:
    active:
    - dev
--- #开发环境
spring:
  profiles:
    application:
      name: microservicecloud-config-dev
--- #测试环境
spring:
  profiles:
    application:
      name: microservicecloud-config-test
#保存为UTF-8格式